# Generated by Django 3.1.7 on 2022-05-10 11:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import django_resized.forms
import plateforme.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, unique=True)),
                ('description_courte', models.TextField()),
                ('description_longue', models.TextField()),
                ('photo_de_couverture', django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format='PNG', keep_meta=True, null=True, quality=100, size=[1920, 1080], upload_to=plateforme.models.upload_to)),
                ('type', models.CharField(choices=[('Sociale', 'Sociale'), ('Environnementale', 'Environnementale')], max_length=50)),
                ('youtube', models.URLField(blank=True, null=True)),
                ('facebook', models.URLField(blank=True, null=True)),
                ('siteweb', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Actualite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, unique=True)),
                ('description_courte', models.TextField()),
                ('description_longue', models.TextField()),
                ('photo_de_couverture', django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format='PNG', keep_meta=True, null=True, quality=100, size=[1920, 1080], upload_to=plateforme.models.upload_to)),
                ('date', models.DateField()),
                ('youtube', models.URLField(blank=True, null=True)),
                ('facebook', models.URLField(blank=True, null=True)),
                ('siteweb', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Artiste',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('photo_de_profil', django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format='PNG', keep_meta=True, null=True, quality=100, size=[500, 500], upload_to=plateforme.models.upload_to)),
                ('youtube', models.URLField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_artiste', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Organisateur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(null=True)),
                ('photo_de_profil', django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format='PNG', keep_meta=True, null=True, quality=100, size=[500, 500], upload_to=plateforme.models.upload_to)),
                ('photo_de_couverture', django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format='PNG', keep_meta=True, null=True, quality=100, size=[1920, 1080], upload_to=plateforme.models.upload_to)),
                ('is_association', models.BooleanField(default=False)),
                ('siteweb', models.URLField(blank=True, null=True)),
                ('facebook', models.URLField(blank=True, null=True)),
                ('youtube', models.URLField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_organisateur', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, unique=True)),
                ('levee_de_fond', models.BooleanField(default=False)),
                ('gratuit', models.BooleanField(default=False)),
                ('duree', models.CharField(blank=True, max_length=200, null=True)),
                ('description_courte', models.TextField()),
                ('description_longue', models.TextField()),
                ('tarif_ariary', models.PositiveIntegerField(blank=True, null=True)),
                ('tarif_dollar', models.PositiveIntegerField(blank=True, null=True)),
                ('tarif_euro', models.PositiveIntegerField(blank=True, null=True)),
                ('date_sortie', models.DateField(blank=True, null=True)),
                ('youtube', models.URLField(blank=True, null=True)),
                ('action', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='action_video', to='plateforme.action')),
                ('artiste', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artiste_video', to='plateforme.artiste')),
                ('artistes', models.ManyToManyField(related_name='artistes_video', to='plateforme.Artiste')),
                ('organisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organisateur_video', to='plateforme.organisateur')),
            ],
        ),
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('photo_de_profil', django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format='PNG', keep_meta=True, null=True, quality=100, size=[500, 500], upload_to=plateforme.models.upload_to)),
                ('pays', django_countries.fields.CountryField(blank=True, max_length=2, null=True)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_profil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Contrat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('sehatra', models.PositiveIntegerField()),
                ('organisateur', models.PositiveIntegerField(blank=True, null=True)),
                ('action', models.PositiveIntegerField(blank=True, null=True)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_contrat', to='plateforme.video')),
            ],
        ),
        migrations.CreateModel(
            name='Association',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(null=True)),
                ('photo_de_profil', django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format='PNG', keep_meta=True, null=True, quality=100, size=[500, 500], upload_to=plateforme.models.upload_to)),
                ('photo_de_couverture', django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format='PNG', keep_meta=True, null=True, quality=100, size=[1920, 1080], upload_to=plateforme.models.upload_to)),
                ('siteweb', models.URLField(blank=True, null=True)),
                ('facebook', models.URLField(blank=True, null=True)),
                ('youtube', models.URLField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_association', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='action',
            name='association',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='associarion_action', to='plateforme.association'),
        ),
    ]
