# Generated by Django 3.1.7 on 2022-05-10 13:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('plateforme', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artiste',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_artiste', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='association',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_association', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='organisateur',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_organisateur', to=settings.AUTH_USER_MODEL),
        ),
    ]
