# Generated by Django 3.1.7 on 2022-05-17 09:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms
import plateforme.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('plateforme', '0004_auto_20220510_1948'),
    ]

    operations = [
        migrations.AddField(
            model_name='artiste',
            name='photo_de_couverture',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format='PNG', keep_meta=True, null=True, quality=100, size=[1920, 1080], upload_to=plateforme.models.upload_to),
        ),
        migrations.CreateModel(
            name='Vue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_vue', to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_vue', to='plateforme.video')),
            ],
        ),
    ]
