# Generated by Django 3.1.7 on 2022-05-17 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plateforme', '0005_auto_20220517_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='devise',
            field=models.CharField(choices=[('Ar', 'Ar'), ('USD', 'USD'), ('EUR', 'EUR')], default='Ar', max_length=50),
        ),
    ]
