# Generated by Django 3.1.7 on 2023-03-26 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plateforme', '0006_profil_devise'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='strip_price_id',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
