# Generated by Django 3.1.7 on 2023-03-26 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plateforme', '0007_video_strip_price_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='strip_price_id',
            new_name='stripe_price_id',
        ),
    ]
