# Generated by Django 3.1.7 on 2023-03-26 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plateforme', '0008_auto_20230326_0926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='stripe_price_id',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
