# Generated by Django 3.1.7 on 2023-03-26 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plateforme', '0009_auto_20230326_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='tarif_dollar',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='tarif_euro',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
