# Generated by Django 3.1.7 on 2023-05-22 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plateforme', '0010_auto_20230326_0938'),
    ]

    operations = [
        migrations.CreateModel(
            name='Live',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('en_ligne', models.BooleanField(default=False)),
                ('date', models.DateField(blank=True, null=True)),
                ('heure', models.TimeField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='video',
            name='is_live',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='video',
            name='live',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='live_video', to='plateforme.live'),
        ),
    ]
