# Generated by Django 3.1.7 on 2023-05-28 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plateforme', '0012_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='live',
            name='debut',
            field=models.BooleanField(default=False),
        ),
    ]
