# Generated by Django 3.1.7 on 2023-09-06 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plateforme', '0015_auto_20230801_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='lien_details',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='action',
            name='lien_don',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='association',
            name='lien_don',
            field=models.URLField(blank=True, null=True),
        ),
    ]
