# Generated by Django 4.2.5 on 2023-10-30 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plateforme', '0016_auto_20230906_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='association',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='association_action', to='plateforme.association'),
        ),
    ]
