# Generated by Django 3.1.7 on 2021-04-17 16:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('concert', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormulaireReclamation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motif', models.CharField(choices=[('Problème de création de compte ou de connexion', 'Problème de création de compte ou de connexion'), ("Problème avec l'achat de billet ou le paiement", "Problème avec l'achat de billet ou le paiement"), ('Problème avec la vidéo', 'Problème avec la vidéo')], max_length=250, null=True)),
                ('message', models.TextField(blank=True, null=True, verbose_name='Description de votre problème')),
                ('date', models.DateField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_formulaire', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
