# Generated by Django 3.1.7 on 2021-04-17 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concert', '0002_formulairereclamation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulairereclamation',
            name='motif',
            field=models.CharField(choices=[('Problème de création de compte ou de connexion', 'Problème de création de compte ou de connexion'), ("Problème avec l'achat de billet ou le paiement", "Problème avec l'achat de billet ou le paiement"), ('Problème avec la vidéo', 'Problème avec la vidéo'), ('Autre', 'Autre')], max_length=250, null=True),
        ),
    ]
