# Generated by Django 3.1.7 on 2021-05-13 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concert', '0003_auto_20210417_2028'),
    ]

    operations = [
        migrations.AddField(
            model_name='concert',
            name='lien_video_dash',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='concert',
            name='lien_video_hls',
            field=models.URLField(blank=True, null=True),
        ),
    ]
