# Generated by Django 3.1.7 on 2022-05-09 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concert', '0004_auto_20210513_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='billet',
            name='gratuit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='paiement',
            name='notif',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
