# Generated by Django 4.2.5 on 2023-10-20 03:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plateforme', '0016_auto_20230906_1319'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PageAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=50)),
                ('screenname', models.TextField()),
                ('utilisateur', models.PositiveIntegerField(blank=True, null=True)),
                ('bouncerate', models.PositiveIntegerField(blank=True, null=True)),
                ('temps_moyenne', models.PositiveIntegerField(blank=True, null=True)),
                ('nouveauutilisateur', models.PositiveIntegerField(blank=True, null=True)),
                ('vue', models.PositiveIntegerField(blank=True, null=True)),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='VenteParPays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=50, unique=True)),
                ('pays', models.TextField()),
                ('date_vente', models.DateTimeField()),
                ('codepays', models.TextField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Video_facebook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.URLField()),
                ('date_publication', models.DateTimeField()),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liens_facebook', to='plateforme.video')),
            ],
        ),
        migrations.CreateModel(
            name='NotificationFCM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('destination_url', models.URLField()),
                ('user', models.ForeignKey(db_column='user', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='utilisateur_notification', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
