# Generated by Django 4.2.5 on 2023-10-30 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venteparpays',
            name='codepays',
            field=models.TextField(max_length=2, null=True),
        ),
    ]
