# Generated by Django 4.2.5 on 2023-11-02 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_alter_venteparpays_codepays'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video_facebook',
            name='date_publication',
            field=models.DateField(),
        ),
    ]
