# Generated by Django 4.2.5 on 2023-11-02 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0003_alter_video_facebook_date_publication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video_facebook',
            name='facebook',
            field=models.TextField(),
        ),
    ]
