"""
Django settings for Sehatra project.

Generated by 'django-admin startproject' using Django 3.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

from datetime import timedelta
import json
from pathlib import Path
import os
from tempfile import NamedTemporaryFile
from firebase_admin import credentials
import firebase_admin
from decouple import config
from django.conf import settings

# Load environment variables from .env file
# Firebase credentials
# settings.py
from decouple import config

FIREBASE_CONFIG = {
    "type": config('FIREBASE_TYPE'),
    "project_id": config('FIREBASE_PROJECT_ID'),
    "private_key_id": config('FIREBASE_PRIVATE_KEY_ID'),
    "private_key": config('FIREBASE_PRIVATE_KEY').replace('\\n', '\n'),
    "client_email": config('FIREBASE_CLIENT_EMAIL'),
    "client_id": config('FIREBASE_CLIENT_ID'),
    "auth_uri": config('FIREBASE_AUTH_URI'),
    "token_uri": config('FIREBASE_TOKEN_URI'),
    "auth_provider_x509_cert_url": config('FIREBASE_AUTH_PROVIDER_x590_CERT_URL'),
    "client_x509_cert_url": config('FIREBASE_CLIENT_x590_CERT_URL'),
    "universe_domain": config('FIREBASE_UNIVERSE_DOMAIN'),
}

# Google Analytics Credentials
GOOGLE_CREDENTIALS = {
  "type": config('GOOGLE_TYPE'),
  "project_id": config('PROJECT_ID'),
  "private_key_id": config('GOOGLE_PRIVATE_KEY_ID'),
  "private_key": config('GOOGLE_PRIVATE_KEY'),
  "client_email": config('GOOGLE_CLIENT_EMAIL'),
  "client_id": config('GOOGLE_CLIENT_ID'),
  "auth_uri": config('GOOGLE_CLIENT_AUTH_URI'),
  "token_uri": config('GOOGLE_TOKEN_URI'),
  "auth_provider_x509_cert_url": config('GOOGLE_AUTH_PROVIDER_x590_CERT_URL'),
  "client_x509_cert_url": config('GOOGLE_CLIENT_x590_CERT_URL'),
  "universe_domain": config('GOOGLE_PROPERTY_ID')
}

AUTH_GOOGLE = {
    "property_id":config('GOOGLE_PROPERTY_ID')
}
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
STATIC_DIR = os.path.join(BASE_DIR, 'static')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '!c(gmx8p^40so%%l-4fhs^hnaza4c(!x5@3+=ip!vmrswg^#nf'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True


def create_google_credentials_temp_file(google_credentials):
    temp_file = NamedTemporaryFile(delete=False, suffix=".json")
    with open(temp_file.name, 'w') as f:
        json.dump(google_credentials, f)
    return temp_file.name

ALLOWED_HOSTS=["localhost","10.166.2.172","192.168.88.75"]
GOOGLE_APPLICATION_CREDENTIALS = create_google_credentials_temp_file(FIREBASE_CONFIG)


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.humanize',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'allauth',
    'crispy_forms',
    'django_user_agents',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    'allauth.socialaccount.providers.facebook',
    'django_object_actions',
    'concert',
    'plateforme',
    'paiement',
    'corsheaders',
    'django.contrib.sitemaps',
    'rest_framework',
    'rest_framework.authtoken',
    'rest_framework_simplejwt',
    'administration',
    'fcm_django',
    'background_task'
]
CRISPY_TEMPLATE_PACK = 'bootstrap4'
FCM_DJANGO_SETTINGS = {
    "DEFAULT_FIREBASE_APP": 'Sehatra.com',
    "APP_VERBOSE_NAME": "FCM Django",
    "ONE_DEVICE_PER_USER": False,  
    "DELETE_INACTIVE_DEVICES": False, 
}

cred = credentials.Certificate(GOOGLE_APPLICATION_CREDENTIALS)
firebase_admin.initialize_app(cred)

REST_FRAMEWORK = {
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10,
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES':(
                'rest_framework.permissions.IsAuthenticated',
    ),
}
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'SLIDING_TOKEN_REFRESH_LIFETIME': timedelta(days=1),
    'SLIDING_TOKEN_LIFETIME': timedelta(days=30),
    'SLIDING_TOKEN_REFRESH_LIFETIME_LATE_USER': timedelta(days=1),
    'SLIDING_TOKEN_LIFETIME_LATE_USER': timedelta(days=30),
}

MIDDLEWARE = [
    'htmlmin.middleware.HtmlMinifyMiddleware',
    'htmlmin.middleware.MarkRequestMiddleware', 
    'corsheaders.middleware.CorsMiddleware',
    'plateforme.middleware.MyMiddleware',
    'allauth.account.middleware.AccountMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'concert.middleware.OneSessionPerUserMiddleware',
    'django_user_agents.middleware.UserAgentMiddleware'
]


ROOT_URLCONF = 'Sehatra.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')]
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
WSGI_APPLICATION = 'Sehatra.wsgi.application'
ALLOWED_HOSTS = ['*']


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}



AUTHENTICATION_BACKENDS = [
    # Needed to login by username in Django admin, regardless of `allauth`
    'django.contrib.auth.backends.ModelBackend',

    # `allauth` specific authentication methods, such as login by e-mail
    'allauth.account.auth_backends.AuthenticationBackend',
]

# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'fr-FR'

TIME_ZONE = 'Indian/Antananarivo'

USE_I18N = True

USE_L10N = True

USE_TZ = True

HTML_MINIFY = False



# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

# STATIC_ROOT = 'C:\\Users\\TOLOTRA-MALAGASY\\PycharmProjects\\Sehatra\\static'
STATIC_URL = '/static/'
# STATIC_ROOT = STATIC_DIR
STATICFILES_DIRS = [STATIC_DIR]

DJANGORESIZED_DEFAULT_FORMAT_EXTENSIONS = {'PNG': ".png"}

MEDIA_ROOT = "media"
MEDIA_URL = "/media/"

ACCOUNT_AUTHENTICATION_METHOD = "email"
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_USERNAME_REQUIRED = False

SITE_ID = 1

LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'

CORS_ORIGIN_ALLOW_ALL = True


SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'SCOPE': [
            'profile',
            'email',
        ],
        'AUTH_PARAMS': {
            'access_type': 'online',
        }
    },

'facebook':
       {'METHOD': 'oauth2',
        'SCOPE': ['email','public_profile'],
        'AUTH_PARAMS': {'auth_type': 'reauthenticate'},
        'FIELDS': [
            'id',
            'email',
            'name',
            'first_name',
            'last_name',
            'verified',
            'locale',
            'timezone',
            'link',
            'gender',
            'updated_time'],
        'EXCHANGE_TOKEN': True,
        'LOCALE_FUNC': lambda request: 'fr_FR',
        'VERIFIED_EMAIL': False,
        'VERSION': 'v2.4'}
}

CRISPY_TEMPLATE_PACK = "bootstrap4"

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'miora.ratsiresy@gmail.com'
EMAIL_HOST_PASSWORD = 'gonnqkiybyhoidxf'
