# Generated by Django 3.1.7 on 2022-05-17 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paiement', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Don',
        ),
    ]
