# Generated by Django 3.1.7 on 2022-05-17 17:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plateforme', '0006_profil_devise'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('paiement', '0002_delete_don'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CodePromo',
        ),
        migrations.DeleteModel(
            name='Influenceur',
        ),
        migrations.AddField(
            model_name='billet',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='billet',
            name='gratuit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='billet',
            name='slug',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='billet',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='utilisateur_billet', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='billet',
            name='valide',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='billet',
            name='video',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='video_billet', to='plateforme.video'),
        ),
        migrations.AddField(
            model_name='modepaiement',
            name='nom',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paiement',
            name='billet',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='billet_paiement', to='paiement.billet'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paiement',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='paiement',
            name='mode',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='mode_paiement', to='paiement.modepaiement'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paiement',
            name='notif_token',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='paiement',
            name='token',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='paiement',
            name='valide',
            field=models.BooleanField(default=False),
        ),
    ]
