# Generated by Django 3.1.7 on 2023-03-26 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paiement', '0003_auto_20220517_2030'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiement',
            name='telephone',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
