# Generated by Django 4.2.5 on 2024-06-18 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("paiement", "0006_alter_billet_date_alter_paiement_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="billet",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="modepaiement",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="paiement",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
